### PR TITLE
lexer: Support ALTER COLUMN statement

### PR DESCRIPTION
**Pull request by vkareh**
The supported way to modify a column in PostgreSQL is to call ALTER
TABLE foo ALTER COLUMN bar. This adds the "column" option to the
invalid-alter-option lexer to prevent erroneous lint failures.

### CODE REVIEW

**Comment by cben** [comment]
ref: https://www.postgresql.org/docs/current/sql-altertable.html

Few example statements that definitely worked on a real Postgres:
```
ALTER TABLE deleted_clusters ALTER COLUMN managed SET DEFAULT TRUE;
ALTER TABLE metrics ALTER COLUMN upgrade_timestamp TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE deleted_clusters ALTER COLUMN api_url SET NOT NULL;
```

LGTM on src/lexer/statements/alter.ts :+1:
Are all these dist/ files changing because of this single source line?

**Comment by vkareh** [comment]
>  Are all these dist/ files changing because of this single source line?

Not all. I think there are some discrepancies due to different versions of npm or global modules. I'll check to see if using a different version affects it.

**Comment by vkareh** [comment]
hmmm... tried node versions 4, 6, 8, 10, and 12... all of them update all the `/dist` similarly as compared to `HEAD~0`. My guess is a OS/platform discrepancy...

**Comment by joereynolds** [comment]
Looks good, I'll merge it in and re-run `build` to generate the `dist` dir again. Not sure what's going on there

**Pull request merged**
